apiVersion: apps/v1
kind: Deployment
metadata:
   name: api-gateway-deploy
   labels:
      type: api-gateway-svc
spec:
  template:
    metadata:
      name: api-gateway-pod
      labels:
        type: api-gateway-svc
    spec:
      containers:
      - name: api-gateway-image
        image: ghcr.io/anasuya-zemo/api-gateway-bc98:latest
        ports:
        - containerPort: 8090
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: https://bc98be.bootcamp64.tk/eureka/    
          - name: EUREKA_INSTANCE_HOSTNAME
            value: api-gateway
      imagePullSecrets: 
      - name: ghcr-secret

  replicas: 1
  selector:
    matchLabels:
      type: api-gateway-svc
