apiVersion: apps/v1
kind: Deployment
metadata:
   name: mockserver-deploy
   labels:
      type: MSD
spec:
  template:
    metadata:
      name: MS-pod
      labels:
        type: MS
    spec:
      containers:
      - name: mockserver-image
        image: ghcr.io/anasuya-zemo/mockserver-bc98:latest
        ports:
        - containerPort: 3000
      imagePullSecrets: 
      - name: ghcr-secret

  replicas: 1
  selector:
    matchLabels:
      type: MS
